# Generated by Django 5.1.6 on 2025-03-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpchars', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hiragana_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='katakana_level',
            field=models.IntegerField(default=100),
        ),
    ]
