# Generated by Django 5.1.6 on 2025-03-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpchars', '0003_user_hiragana_level_user_katakana_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('representation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('min_level', models.IntegerField()),
                ('japanese', models.CharField(max_length=255)),
                ('romaji', models.CharField(max_length=255)),
            ],
        ),
    ]
