# Generated by Django 5.1.6 on 2025-03-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpchars', '0005_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='hint',
            field=models.CharField(default='', max_length=255),
        ),
    ]
