# Generated by Django 5.1.6 on 2025-03-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bidden',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='user',
            name='commented',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.comment'),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('bids', models.ManyToManyField(blank=True, related_name='listings', to='auctions.bid')),
                ('comments', models.ManyToManyField(blank=True, related_name='listings', to='auctions.comment')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='owned',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.listing'),
        ),
    ]
