# Generated by Django 5.1.6 on 2025-03-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_user_bidden_user_commented_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
