# Generated by Django 5.1.6 on 2025-03-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlisted',
            field=models.ManyToManyField(blank=True, related_name='watchlisters', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bidden',
            field=models.ManyToManyField(blank=True, related_name='bidders', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='commented',
            field=models.ManyToManyField(blank=True, related_name='commenters', to='auctions.comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='owned',
            field=models.ManyToManyField(blank=True, related_name='owners', to='auctions.listing'),
        ),
    ]
